/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UnauthenticatedRouteRouteImport } from './routes/_unauthenticated/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as UnauthenticatedIndexRouteImport } from './routes/_unauthenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedStatsIndexRouteImport } from './routes/_authenticated/stats/index'
import { Route as AuthenticatedSpotifyIndexRouteImport } from './routes/_authenticated/spotify/index'
import { Route as AuthenticatedSliversIndexRouteImport } from './routes/_authenticated/slivers/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDashIndexRouteImport } from './routes/_authenticated/dash/index'
import { Route as AuthenticatedCommentsIndexRouteImport } from './routes/_authenticated/comments/index'
import { Route as AuthenticatedArticlesIndexRouteImport } from './routes/_authenticated/articles/index'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedArticlesTagsRouteImport } from './routes/_authenticated/articles/tags'
import { Route as AuthenticatedArticlesNewRouteImport } from './routes/_authenticated/articles/new'
import { Route as AuthenticatedArticlesMediaRouteImport } from './routes/_authenticated/articles/media'
import { Route as AuthenticatedArticlesListRouteImport } from './routes/_authenticated/articles/list'
import { Route as AuthenticatedArticlesCategoriesRouteImport } from './routes/_authenticated/articles/categories'
import { Route as AuthenticatedArticlesArticleIdEditRouteImport } from './routes/_authenticated/articles/$articleId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRouteRoute = UnauthenticatedRouteRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedIndexRoute = UnauthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnauthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsIndexRoute = AuthenticatedStatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpotifyIndexRoute =
  AuthenticatedSpotifyIndexRouteImport.update({
    id: '/spotify/',
    path: '/spotify/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSliversIndexRoute =
  AuthenticatedSliversIndexRouteImport.update({
    id: '/slivers/',
    path: '/slivers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashIndexRoute = AuthenticatedDashIndexRouteImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommentsIndexRoute =
  AuthenticatedCommentsIndexRouteImport.update({
    id: '/comments/',
    path: '/comments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArticlesIndexRoute =
  AuthenticatedArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedArticlesTagsRoute =
  AuthenticatedArticlesTagsRouteImport.update({
    id: '/articles/tags',
    path: '/articles/tags',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArticlesNewRoute =
  AuthenticatedArticlesNewRouteImport.update({
    id: '/articles/new',
    path: '/articles/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArticlesMediaRoute =
  AuthenticatedArticlesMediaRouteImport.update({
    id: '/articles/media',
    path: '/articles/media',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArticlesListRoute =
  AuthenticatedArticlesListRouteImport.update({
    id: '/articles/list',
    path: '/articles/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArticlesCategoriesRoute =
  AuthenticatedArticlesCategoriesRouteImport.update({
    id: '/articles/categories',
    path: '/articles/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArticlesArticleIdEditRoute =
  AuthenticatedArticlesArticleIdEditRouteImport.update({
    id: '/articles/$articleId/edit',
    path: '/articles/$articleId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof UnauthenticatedIndexRoute
  '/articles/categories': typeof AuthenticatedArticlesCategoriesRoute
  '/articles/list': typeof AuthenticatedArticlesListRoute
  '/articles/media': typeof AuthenticatedArticlesMediaRoute
  '/articles/new': typeof AuthenticatedArticlesNewRoute
  '/articles/tags': typeof AuthenticatedArticlesTagsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/articles': typeof AuthenticatedArticlesIndexRoute
  '/comments': typeof AuthenticatedCommentsIndexRoute
  '/dash': typeof AuthenticatedDashIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/slivers': typeof AuthenticatedSliversIndexRoute
  '/spotify': typeof AuthenticatedSpotifyIndexRoute
  '/stats': typeof AuthenticatedStatsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/articles/$articleId/edit': typeof AuthenticatedArticlesArticleIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof UnauthenticatedIndexRoute
  '/articles/categories': typeof AuthenticatedArticlesCategoriesRoute
  '/articles/list': typeof AuthenticatedArticlesListRoute
  '/articles/media': typeof AuthenticatedArticlesMediaRoute
  '/articles/new': typeof AuthenticatedArticlesNewRoute
  '/articles/tags': typeof AuthenticatedArticlesTagsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/articles': typeof AuthenticatedArticlesIndexRoute
  '/comments': typeof AuthenticatedCommentsIndexRoute
  '/dash': typeof AuthenticatedDashIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/slivers': typeof AuthenticatedSliversIndexRoute
  '/spotify': typeof AuthenticatedSpotifyIndexRoute
  '/stats': typeof AuthenticatedStatsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/articles/$articleId/edit': typeof AuthenticatedArticlesArticleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_unauthenticated/': typeof UnauthenticatedIndexRoute
  '/_authenticated/articles/categories': typeof AuthenticatedArticlesCategoriesRoute
  '/_authenticated/articles/list': typeof AuthenticatedArticlesListRoute
  '/_authenticated/articles/media': typeof AuthenticatedArticlesMediaRoute
  '/_authenticated/articles/new': typeof AuthenticatedArticlesNewRoute
  '/_authenticated/articles/tags': typeof AuthenticatedArticlesTagsRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/articles/': typeof AuthenticatedArticlesIndexRoute
  '/_authenticated/comments/': typeof AuthenticatedCommentsIndexRoute
  '/_authenticated/dash/': typeof AuthenticatedDashIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/slivers/': typeof AuthenticatedSliversIndexRoute
  '/_authenticated/spotify/': typeof AuthenticatedSpotifyIndexRoute
  '/_authenticated/stats/': typeof AuthenticatedStatsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/articles/$articleId/edit': typeof AuthenticatedArticlesArticleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/articles/categories'
    | '/articles/list'
    | '/articles/media'
    | '/articles/new'
    | '/articles/tags'
    | '/settings/appearance'
    | '/settings/profile'
    | '/articles'
    | '/comments'
    | '/dash'
    | '/help-center'
    | '/settings/'
    | '/slivers'
    | '/spotify'
    | '/stats'
    | '/users'
    | '/articles/$articleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/articles/categories'
    | '/articles/list'
    | '/articles/media'
    | '/articles/new'
    | '/articles/tags'
    | '/settings/appearance'
    | '/settings/profile'
    | '/articles'
    | '/comments'
    | '/dash'
    | '/help-center'
    | '/settings'
    | '/slivers'
    | '/spotify'
    | '/stats'
    | '/users'
    | '/articles/$articleId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_unauthenticated/'
    | '/_authenticated/articles/categories'
    | '/_authenticated/articles/list'
    | '/_authenticated/articles/media'
    | '/_authenticated/articles/new'
    | '/_authenticated/articles/tags'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/profile'
    | '/_authenticated/articles/'
    | '/_authenticated/comments/'
    | '/_authenticated/dash/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/slivers/'
    | '/_authenticated/spotify/'
    | '/_authenticated/stats/'
    | '/_authenticated/users/'
    | '/_authenticated/articles/$articleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthenticatedRouteRoute: typeof UnauthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/': {
      id: '/_unauthenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedIndexRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats/': {
      id: '/_authenticated/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spotify/': {
      id: '/_authenticated/spotify/'
      path: '/spotify'
      fullPath: '/spotify'
      preLoaderRoute: typeof AuthenticatedSpotifyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slivers/': {
      id: '/_authenticated/slivers/'
      path: '/slivers'
      fullPath: '/slivers'
      preLoaderRoute: typeof AuthenticatedSliversIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dash/': {
      id: '/_authenticated/dash/'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof AuthenticatedDashIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comments/': {
      id: '/_authenticated/comments/'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof AuthenticatedCommentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/': {
      id: '/_authenticated/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/articles/tags': {
      id: '/_authenticated/articles/tags'
      path: '/articles/tags'
      fullPath: '/articles/tags'
      preLoaderRoute: typeof AuthenticatedArticlesTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/new': {
      id: '/_authenticated/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof AuthenticatedArticlesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/media': {
      id: '/_authenticated/articles/media'
      path: '/articles/media'
      fullPath: '/articles/media'
      preLoaderRoute: typeof AuthenticatedArticlesMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/list': {
      id: '/_authenticated/articles/list'
      path: '/articles/list'
      fullPath: '/articles/list'
      preLoaderRoute: typeof AuthenticatedArticlesListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/categories': {
      id: '/_authenticated/articles/categories'
      path: '/articles/categories'
      fullPath: '/articles/categories'
      preLoaderRoute: typeof AuthenticatedArticlesCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/$articleId/edit': {
      id: '/_authenticated/articles/$articleId/edit'
      path: '/articles/$articleId/edit'
      fullPath: '/articles/$articleId/edit'
      preLoaderRoute: typeof AuthenticatedArticlesArticleIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedArticlesCategoriesRoute: typeof AuthenticatedArticlesCategoriesRoute
  AuthenticatedArticlesListRoute: typeof AuthenticatedArticlesListRoute
  AuthenticatedArticlesMediaRoute: typeof AuthenticatedArticlesMediaRoute
  AuthenticatedArticlesNewRoute: typeof AuthenticatedArticlesNewRoute
  AuthenticatedArticlesTagsRoute: typeof AuthenticatedArticlesTagsRoute
  AuthenticatedArticlesIndexRoute: typeof AuthenticatedArticlesIndexRoute
  AuthenticatedCommentsIndexRoute: typeof AuthenticatedCommentsIndexRoute
  AuthenticatedDashIndexRoute: typeof AuthenticatedDashIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedSliversIndexRoute: typeof AuthenticatedSliversIndexRoute
  AuthenticatedSpotifyIndexRoute: typeof AuthenticatedSpotifyIndexRoute
  AuthenticatedStatsIndexRoute: typeof AuthenticatedStatsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedArticlesArticleIdEditRoute: typeof AuthenticatedArticlesArticleIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedArticlesCategoriesRoute: AuthenticatedArticlesCategoriesRoute,
  AuthenticatedArticlesListRoute: AuthenticatedArticlesListRoute,
  AuthenticatedArticlesMediaRoute: AuthenticatedArticlesMediaRoute,
  AuthenticatedArticlesNewRoute: AuthenticatedArticlesNewRoute,
  AuthenticatedArticlesTagsRoute: AuthenticatedArticlesTagsRoute,
  AuthenticatedArticlesIndexRoute: AuthenticatedArticlesIndexRoute,
  AuthenticatedCommentsIndexRoute: AuthenticatedCommentsIndexRoute,
  AuthenticatedDashIndexRoute: AuthenticatedDashIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedSliversIndexRoute: AuthenticatedSliversIndexRoute,
  AuthenticatedSpotifyIndexRoute: AuthenticatedSpotifyIndexRoute,
  AuthenticatedStatsIndexRoute: AuthenticatedStatsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedArticlesArticleIdEditRoute:
    AuthenticatedArticlesArticleIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UnauthenticatedRouteRouteChildren {
  UnauthenticatedIndexRoute: typeof UnauthenticatedIndexRoute
}

const UnauthenticatedRouteRouteChildren: UnauthenticatedRouteRouteChildren = {
  UnauthenticatedIndexRoute: UnauthenticatedIndexRoute,
}

const UnauthenticatedRouteRouteWithChildren =
  UnauthenticatedRouteRoute._addFileChildren(UnauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthenticatedRouteRoute: UnauthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
